# fly.toml app configuration file generated for mi-chad-bot on 2026-05-22T09:56:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mi-chad-bot'
primary_region = 'gru'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
